In [ ]:
import pandas as pd

df = pd.read_csv("zomato.csv")

In [ ]:
df.head()

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [ ]:
df.isna().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [57]:
df.dropna(inplace=True)

In [ ]:
df.isna().sum()

Unnamed: 0.1             0
Unnamed: 0               0
restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
dtype: int64

Here the missing values are replaced with '0' using isna()

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
text=["restaurant name", "restaurant type","cuisines type","area","local address"]
for x in text:
  df[x]=df[x].str.strip().str.title().str.lower()

Created a list so that weecan easily clean all the rrequired columns

In [ ]:
df=df.convert_dtypes()

In [ ]:
df.rename(columns={
    'Unnamed: 0.1'       : 'index_1',
    'Unnamed: 0'         : 'index_2',
    'restaurant name'    : 'restaurant_name',
    'restaurant type'    : 'restaurant_type',
    'rate (out of 5)'    : 'rating',
    'num of ratings'     : 'num_ratings',
    'avg cost (two people)' : 'avg_cost_two',
    'table booking'      : 'table_booking',
    'cuisines type'      : 'cuisines_type',
    'local address'      : 'local_address',
}, inplace=True)

In [58]:
df['hybrid'] = (df['online_order'] == 'Yes') & (df['table_booking'] == 'Yes')

Created a new column to see whether restuarants offer both online &offline mode of transportation or not

In [ ]:
df.to_csv('cleaned_dataset.csv', index=False)